# Generated by Django 5.1.3 on 2024-12-23 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0003_developer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TrafficOfficer',
        ),
        migrations.AlterField(
            model_name='trafficreport',
            name='assigned_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic_control.trafficpolice'),
        ),
    ]
